# Generated by Django 5.0.6 on 2024-06-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='data',
            new_name='index',
        ),
    ]
